### ISSUE TITLE
Credentials Exposed

### ISSUE THREAD

**Issue by csquared** [kashiwale/dhiren-kashiwale1#2]
https://github.com/kashiwale/dhiren-kashiwale1/blob/6d77d94c5c0e13beb54b5ccfd1e915cf71ee6c18/dj_pd/.env#L9-L12

Hi there:
Chris from Bucketeer here. These credentials are on the public internet. I've rolled them and new ones are available in your Heroku app - please keep them private in the future!
Cheers,
Chris

**Comment by kashiwale** [comment]
Thank You Chris
